version: '3.8'

services:
  # Serviço principal do banco de dados PostgreSQL
  postgres:
    image: postgres:16  # Versão específica do PostgreSQL
    container_name: agendasis_postgres  # Nome do container para fácil referência
    
    # Mapeamento de porta - host:container
    ports:
      - "5432:5432"
    
    # Variáveis de ambiente para configuração do PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: agendasis_db
    
    # Volume persistente para armazenar os dados
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    # Configurações de saúde do container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    # Configurações adicionais
    restart: unless-stopped  # Reinicia automaticamente em caso de falha

# Definição dos volumes
volumes:
  postgres_data:
    # Volume nomeado para persistência dos dados
    name: agendasis_postgres_data 