services:
  - type: web
    name: agendasis-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: agendasis-backend
    env: php
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:$PORT -t server/
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: agendasis-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: agendasis-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: agendasis-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: agendasis-db
          property: database

databases:
  - name: agendasis-db
    plan: free 